name: Github Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          wget -qO- http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest |
            awk -F '|' '$2=="CN" && $3=="ipv4" {printf "%s/%s\n", $4, 32-log($5)/log(2)}' > ignore.list
      - id: date
        run: echo "::set-output name=dt::$(TZ=UTC date +%F)"
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.dt }}
          files: |
            ignore.list
      - uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: github
          slack-message: 'github release ok'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
